-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.
-- Multi-user schema: user_id is Telegram from.id (BIGINT).

-- Users: one row per Telegram user (for reminders and identity)
CREATE TABLE users (
    user_id BIGINT PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    username TEXT,
    first_seen_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table Definition ----------------------------------------------

CREATE TABLE raw_data (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    timestamp bigint,
    "yearmonth" int,
    "yearweek" int,
    "year" smallint,
    "quarter" smallint,
    "month" smallint,
    "day" smallint,
    "hour" smallint,
    "minute" smallint,
    "week" smallint,
    "key" text,
    "question" text,
    "type" text,
    "value" text,
    "matcheddate" date,
    "source" text,
    "importedat" timestamp,
    "importid" text
);

CREATE INDEX idx_raw_data_user_key_timestamp ON raw_data (user_id, "key", timestamp DESC);

-- Table Definition ----------------------------------------------

CREATE TABLE last_run (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    command text NOT NULL,
    last_run bigint,
    last_message bigint,
    UNIQUE (user_id, command)
);


-- View needed for metrics

create or replace function cast_to_int(text) returns integer as $$
begin
    -- Note the double casting to avoid infinite recursion.
    return cast($1::varchar as integer);
exception
    when invalid_text_representation then
        return 0;
end;
$$ language plpgsql immutable;

create or replace function cast_to_float(text) returns float as $$
begin
    -- Note the double casting to avoid infinite recursion.
    return cast($1::varchar as integer);
exception
    when invalid_text_representation then
        return 0;
end;
$$ language plpgsql immutable;

CREATE VIEW raw_data_for_metabase AS
  SELECT *,
  cast_to_int(value) AS valueAsInt,
  cast_to_float(value) AS valueAsFloat
  FROM raw_data
